version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    command: uv run uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  test:
    build: .
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    command: uv run pytest test_2_main.py -v
